const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const out=path.join(root,'dist-pages');
assert.ok(fs.existsSync(path.join(out,'index.html')),'public build must contain the full application shell');
assert.ok(fs.existsSync(path.join(out,'app.js')),'public build must contain the application script');
assert.ok(fs.existsSync(path.join(out,'app.css')),'public build must contain the application stylesheet');
assert.ok(fs.existsSync(path.join(out,'tts-edge.js')),'public build must contain the Neural TTS enhancement');
const publicApp=fs.readFileSync(path.join(out,'app.js'),'utf8');
const publicUi=fs.readFileSync(path.join(out,'ui-enhancements.js'),'utf8');
const publicOverlayScript=fs.readFileSync(path.join(out,'overlays','advanced.js'),'utf8');
const publicTts=fs.readFileSync(path.join(out,'tts-edge.js'),'utf8');
assert.match(publicApp,/tiklivetools_public_backend/,'public app must reuse the Actions backend setting for overlay links');
assert.match(publicTts,/ttsApi\('\/api\/tts\/voices'\)/,'public TTS catalog must use the configured backend');
assert.match(publicTts,/ttsApi\('\/api\/tts\/synthesize'\)/,'public TTS synthesis must use the configured backend');
assert.match(publicApp,/Testează \$\{label\}/,'gallery buttons must be named for the selected overlay');
assert.match(publicApp,/previewOverlay=overlay/,'gallery tests must target only the selected overlay');
assert.match(publicApp,/join:new Set\(\['viewer-count'\]\)/,'viewer count must use the real join event');
assert.match(publicApp,/type==='join'\?\{type:'join'/,'viewer count test must emit a join event');
assert.doesNotMatch(publicApp,/data-test="gift" data-overlay="\$\{name\}">Test gift/,'gallery must not render generic Test gift buttons');
assert.match(publicOverlayScript,/const eventCues=\{/,'overlay sounds must use an event-specific cue map');
assert.match(publicOverlayScript,/firework:\{gift:'firework'\}/,'firework must have its own gift cue');
assert.match(publicOverlayScript,/'like-fountain':\{like:'fountain'\}/,'like fountain must have its own like cue');
assert.doesNotMatch(publicOverlayScript,/name==='top-likes'\|\|name==='leaderboard'/,'static leaderboard overlays must not replay a sound for every like');
assert.match(publicOverlayScript,/m\.type==='tts'&&name==='action-screen'/,'TTS must be restricted to the Actions overlay');
assert.match(publicOverlayScript,/m\.type==='tts'&&name==='action-screen'&&\(!screenId\|\|!target\|\|screenId===target\)/,'Actions TTS must respect its target screen');
assert.match(publicOverlayScript,/m\.type==='tts'&&name==='action-screen'&&!previewMode/,'gallery preview mode must suppress Actions Screen TTS');
assert.doesNotMatch(publicOverlayScript,/m\.type==='tts'\)speakOverlayTts/,'ordinary overlays must not replay global TTS messages');
assert.match(publicOverlayScript,/m\.type==='sound'&&name==='action-screen'/,'global sound alerts must be isolated to the Actions overlay');
assert.doesNotMatch(publicApp,/m\.type==='tts'/,'the control panel must not replay TTS received by overlays');
assert.doesNotMatch(publicApp,/m\.type==='sound'&&m\.sound/,'the control panel must not replay sound alerts received by overlays');
assert.match(publicUi,/secretsOmitted:true/,'configuration exports must explicitly omit local secrets');
assert.match(publicApp,/secretsOmitted:true/,'base configuration export must omit local secrets before UI enhancements load');
assert.match(publicApp,/spotifyAccessToken/,'base configuration export must filter Spotify secrets');
assert.ok(fs.existsSync(path.join(out,'assets','gifts','manifest.json')),'public build must contain gift assets');
assert.equal(fs.readFileSync(path.join(out,'CNAME'),'utf8').trim(),'live.panel-pro.ro','public build must target the configured domain');
for(const slug of ['firework','gift-cannon','gift-battle','gift-browser','coin-jar','top-likes','timer','wheel','song-requests','challenge','halving']){
  const file=path.join(out,'overlay',slug,'index.html');
  assert.ok(fs.existsSync(file),`public overlay route missing: ${slug}`);
  assert.match(fs.readFileSync(file,'utf8'),/advanced\.js/);
}
console.log('TikLiveTools public build tests passed');
