const assert=require('node:assert/strict');
const base=process.env.TEST_BASE_URL||'http://localhost:3000';
async function get(path){const r=await fetch(base+path);assert.equal(r.ok,true,`${path} returned ${r.status}`);return r.json()}
async function post(path,body){const r=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body||{})});assert.equal(r.ok,true,`${path} returned ${r.status}`);return r.json()}
async function expectStatus(path,body,status){const r=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body||{})});assert.equal(r.status,status,`${path} expected ${status}, got ${r.status}`);return r.json()}
(async()=>{
  const status=await get('/api/status');const profiles=await get('/api/profiles');assert.ok(profiles[0]&&Object.prototype.hasOwnProperty.call(profiles[0],'session_id'),'profiles must support local TikTok session storage');const viewers=await get('/api/viewers?limit=5');assert.ok(Array.isArray(viewers),'viewer database endpoint must return an array');const profileName='Smoke Profile '+Date.now();const profile=await post('/api/profiles',{name:profileName,username:'smoke_profile',plan:'premium'});const profileAgain=await post('/api/profiles',{name:profileName,username:'smoke_profile_updated',plan:'premium'});assert.equal(Number(profileAgain.id),Number(profile.id),'re-importing a profile must update it instead of duplicating');
  const health=await get('/api/health');assert.equal(health.database,true,'health endpoint must report MariaDB');assert.equal(typeof health.tiktok,'boolean');assert.ok(health.tiktokError===null||typeof health.tiktokError==='string');assert.equal(typeof health.obs,'boolean');assert.ok(health.obsError===null||typeof health.obsError==='string');assert.equal(typeof health.tts,'boolean');
  const privateSettings=await get('/api/settings');await post('/api/settings',{tiktokSessionId:'smoke-public-secret'});const publicSettingsResponse=await fetch(base+'/api/settings',{headers:{origin:process.env.PUBLIC_ORIGIN||'https://live.panel-pro.ro'}});const publicSettings=await publicSettingsResponse.json();assert.equal(publicSettings.tiktokSessionId,undefined,'public settings must redact TikTok sessionid');await post('/api/settings',{tiktokSessionId:privateSettings.tiktokSessionId||''});
  assert.equal(status.db,true,'MariaDB is not connected');
  const previewId=`smoke_preview_${Date.now()}`;await post('/api/test-event',{type:'gift',uniqueId:previewId,displayName:'Preview Only',giftName:'Rose',coins:5,previewOnly:true,previewOverlay:'firework'});const previewViewers=await get(`/api/viewers?limit=10&q=${encodeURIComponent(previewId)}`);assert.equal(previewViewers.length,0,'overlay preview events must not persist in MariaDB');
  const spotify=await get('/api/spotify/status');assert.equal(typeof spotify.configured,'boolean','Spotify status must be available');
  const hotkeys=await get('/api/hotkeys');assert.ok(hotkeys.bindings['1'],'global hotkey bridge must expose bindings');
  const manifest=await get('/assets/gifts/manifest.json');
  assert.equal(manifest.length,966,'Gift manifest must contain 966 assets');
  for(const path of ['/api/rules','/api/goals','/api/chat/commands','/api/songs','/api/sounds','/api/overlays'])assert.ok(Array.isArray(await get(path)),`${path} must return an array`);
  assert.ok(status.roomStats&&Array.isArray(status.roomStats.topGifters),'status must expose room statistics');
  const connectError=await expectStatus('/api/connect',{username:'',sessionId:''},400);assert.match(connectError.error,/username/i,'TikTok must validate the username before attempting a network connection');
  const oldSettings=await get('/api/settings');await post('/api/settings',{pointsPerLike:2,levelBasePoints:10,levelMultiplier:1.25,subscriberBonusPercent:50});await post('/api/test-event',{type:'like',uniqueId:'smoke_points_user',quantity:6,isSubscriber:true});const pointStats=await get('/api/viewers/stats');const pointUser=pointStats.points.find(x=>x.uniqueId==='smoke_points_user');assert.ok(pointUser&&Number(pointUser.points)>=18&&Number(pointUser.level)>=2,'points, subscriber bonus and levels must update');for(const [key,value] of Object.entries(oldSettings))await post('/api/settings',{[key]:value});
  const songUser='smoke_song_user';await post('/api/settings',{pointsPerLike:2});await post('/api/test-event',{type:'like',uniqueId:songUser,displayName:'Song Viewer',quantity:10});const song=await post('/api/songs/request',{uniqueId:songUser,displayName:'Song Viewer',title:'Smoke Request',artist:'Local Test',pointsCost:12});assert.ok(song.id,'song request with enough points must be accepted');const rejected=await expectStatus('/api/songs/request',{uniqueId:songUser,displayName:'Song Viewer',title:'Too Expensive',pointsCost:100},400);assert.match(rejected.error,/points/i,'song request must reject insufficient points');for(const [key,value] of Object.entries(oldSettings))await post('/api/settings',{[key]:value});
  const goal=await post('/api/goals',{name:'Smoke likes goal',goalType:'likes',target:999,currentValue:0,resetMode:'manual'});await post('/api/test-event',{type:'like',uniqueId:'smoke_goal_user',quantity:3});const goals=await get('/api/goals');assert.ok(goals.some(g=>Number(g.id)===Number(goal.id)&&Number(g.current_value)>=3),'likes must update goal state');await fetch(`${base}/api/goals/${goal.id}`,{method:'DELETE'});
  const command=await post('/api/chat/commands',{commandName:'!smoke',responseText:'Salut {username}',requiredRole:'everyone',cooldownSeconds:1,actions:[]});const commandAgain=await post('/api/chat/commands',{commandName:'!smoke',responseText:'Salut din nou {username}',requiredRole:'everyone',cooldownSeconds:2,actions:[]});assert.equal(Number(commandAgain.id),Number(command.id),'re-importing a command must update it instead of duplicating');assert.ok((await get('/api/chat/commands')).some(c=>Number(c.id)===Number(command.id)&&c.response_text==='Salut din nou {username}'),'chat command must persist');await fetch(`${base}/api/chat/commands/${command.id}`,{method:'DELETE'});
  const rule=await post('/api/rules',{name:'Smoke rule',triggerType:'gift',triggerConfig:{minCoins:2},actions:[{type:'tts',text:'hello'}],cooldownSeconds:4});const ruleAgain=await post('/api/rules',{name:'Smoke rule',triggerType:'gift',triggerConfig:{minCoins:8},actions:[{type:'tts',text:'updated'}],cooldownSeconds:5});assert.equal(Number(ruleAgain.id),Number(rule.id),'re-importing a rule must update it instead of duplicating');assert.ok((await get('/api/rules')).some(x=>Number(x.id)===Number(rule.id)&&Number(x.cooldown_seconds)===5),'automation rule must persist updated values');await fetch(`${base}/api/rules/${rule.id}`,{method:'DELETE'});
  const goalImport=await post('/api/goals',{name:'Smoke import goal',goalType:'coins',target:100});const goalImportAgain=await post('/api/goals',{name:'Smoke import goal',goalType:'coins',target:200});assert.equal(Number(goalImportAgain.id),Number(goalImport.id),'re-importing a goal must update it instead of duplicating');await fetch(`${base}/api/goals/${goalImport.id}`,{method:'DELETE'});
  const sound=await post('/api/sounds',{name:'Smoke sound',triggerType:'gift',triggerConfig:{minCoins:1},filePath:'/uploads/sounds/smoke.mp3',volume:.6});assert.ok((await get('/api/sounds')).some(s=>Number(s.id)===Number(sound.id)),'sound alert must persist');const soundTest=await post(`/api/sounds/${sound.id}/test`,{});assert.equal(soundTest.ok,true,'sound alert test must broadcast without a live event');await fetch(`${base}/api/sounds/${sound.id}`,{method:'DELETE'});
  await post('/api/overlays',{slug:'smoke-overlay',title:'Smoke Overlay',config:{animation:'pulse'}});assert.ok((await get('/api/overlays')).some(o=>o.slug==='smoke-overlay'),'overlay config must persist');const overlayDelete=await fetch(`${base}/api/overlays/smoke-overlay`,{method:'DELETE'});assert.equal(overlayDelete.status,200,'overlay config must be deletable');
  const requiredOverlays=['firework','gift-cannon','gift-battle','gift-browser','top-likes','top-coins','coin-jar','alerts','goals','leaderboard','win-goal','countdown-goal','follower-count','gift-count','last-follower','last-liker','last-gifter','gift-feed','like-fountain','likeathon','penalty-battle','coin-match','points-animation','user-info','command-info','action-screen','interaction-slider','drop','song-requests','viewer-count','stream-buddies','timer','wheel','top-gifters','challenge','halving','snow','social','emojify'];assert.equal(requiredOverlays.length,39);for(const slug of requiredOverlays){const r=await fetch(`${base}/overlay/${slug}`);assert.equal(r.status,200,`overlay ${slug} unavailable`)}
  const wheel=await post('/api/games/wheel/start',{options:['Smoke A','Smoke B']});const spun=await post(`/api/games/${wheel.id}/spin`,{});assert.ok(['Smoke A','Smoke B'].includes(spun.game.state.result),'wheel spin must return configured option');await post(`/api/games/${wheel.id}/finish`,{});
  const timer=await post('/api/games/timer/start',{durationSeconds:30});const overlay=await get('/api/overlay/timer/data');assert.ok((overlay.games||[]).some(x=>Number(x.id)===Number(timer.id)),'timer must appear in overlay state');await post(`/api/games/${timer.id}/finish`,{});
  const likeathon=await post('/api/games/likeathon/start',{target:100});await post('/api/test-event',{type:'like',uniqueId:'smoke_likeathon',quantity:7});let likeathonState=await get('/api/games/likeathon');likeathonState=typeof likeathonState.state==='string'?JSON.parse(likeathonState.state):likeathonState.state;assert.equal(Number(likeathonState.score),7,'likeathon must count likes');await post(`/api/games/${likeathon.id}/finish`,{});
  for(const type of ['challenge','coinmatch','penalty','halving']){const game=await post(`/api/games/${type}/start`,{target:100});await post('/api/test-event',{type:'gift',uniqueId:`smoke_${type}`,coins:8,giftName:'Rose'});const state=await get(`/api/games/${type}`);const parsed=typeof state.state==='string'?JSON.parse(state.state):state.state;assert.ok(Number(parsed.score)>=8,`${type} must count gift coins`);await post(`/api/games/${game.id}/finish`,{})}
  const drop=await post('/api/games/drop/start',{dropPoints:7});await post('/api/test-event',{type:'chat',uniqueId:'smoke_drop_user',comment:'hello'});await post('/api/test-event',{type:'chat',uniqueId:'smoke_drop_user',comment:'hello'});const dropState=await get('/api/games/drop');const parsedDrop=typeof dropState.state==='string'?JSON.parse(dropState.state):dropState.state;assert.equal(Number(parsedDrop.score),7,'points drop must award once per viewer');await post(`/api/games/${drop.id}/finish`,{});
  const nextSong=await post('/api/songs/next',{});assert.ok(Object.prototype.hasOwnProperty.call(nextSong,'id'),'song next endpoint must return queue state');
  console.log('TikLiveTools smoke tests passed');
})().catch(error=>{console.error(error);process.exit(1)})
