const assert=require('node:assert/strict');
const {normalizeGift,normalizeLike}=require('../src/tiktok');
const {template,matches}=require('../src/actions');
const SpotifyService=require('../src/spotify');
const gift=normalizeGift({giftId:7,giftDetails:{giftType:1,giftName:'Rose'},repeatCount:4,repeatEnd:true,diamondCount:4,user:{uniqueId:'viewer',nickname:'Viewer'}});
assert.equal(gift.giftName,'Rose');assert.equal(gift.quantity,4);assert.equal(gift.giftType,1);assert.equal(gift.repeatEnd,true);
const like=normalizeLike({likeCount:25,totalLikeCount:200,user:{uniqueId:'viewer',nickname:'Viewer'}});assert.equal(like.quantity,25);assert.equal(like.totalLikeCount,200);
assert.equal(template('Mulțumesc {username}: {gift} ({coins})',{username:'Viewer',gift:'Rose',coins:4}),'Mulțumesc Viewer: Rose (4)');
assert.equal(matches({enabled:1,trigger_type:'gift',trigger_config:{minCoins:5}},{type:'gift',coins:4}),false);
assert.equal(matches({enabled:1,trigger_type:'gift',trigger_config:{minCoins:5}},{type:'gift',coins:5}),true);
(async()=>{const messages=[];const {ActionEngine}=require('../src/actions');const engine=new ActionEngine({getRules:async()=>[],broadcast:m=>messages.push(m),obs:null});await engine.execute({type:'sound',url:'/uploads/sounds/test.mp3',volume:.5},{type:'gift',displayName:'Viewer'});assert.equal(messages[0].type,'sound');assert.equal(messages[0].sound.url,'/uploads/sounds/test.mp3');assert.equal(messages[0].sound.volume,.5);const spotify=new SpotifyService({getSettings:async()=>({})});assert.equal((await spotify.status()).configured,false);await assert.rejects(()=>spotify.authorizationUrl(),/SPOTIFY_CLIENT_ID/);console.log('TikLiveTools unit tests passed')})().catch(error=>{console.error(error);process.exit(1)});
