const path=require('path');
const fs=require('fs');
const http=require('http');
const express=require('express');
const WebSocket=require('ws');
const multer=require('multer');
require('dotenv').config();
const db=require('./db');
const migrate=require('./migrate');
const TikTokService=require('./tiktok');
const ObsService=require('./obs');
const HotkeyService=require('./hotkeys');
const {ActionEngine}=require('./actions');
const DiscordNotifier=require('./discord');

const app=express();
const soundDir=path.join(__dirname,'..','public','uploads','sounds');fs.mkdirSync(soundDir,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:soundDir,filename:(_req,file,cb)=>{const safe=path.basename(file.originalname).replace(/[^a-zA-Z0-9._-]/g,'_');cb(null,`${Date.now()}-${safe}`)}}),limits:{fileSize:15*1024*1024},fileFilter:(_req,file,cb)=>cb(null,/^audio\//i.test(file.mimetype))});
const server=http.createServer(app);
const wss=new WebSocket.Server({server,path:'/ws'});
const clients=new Set();
const state={connected:false,obsConnected:false,username:process.env.TIKTOK_USERNAME||'',lastEvent:null,db:false,gifts:[]};
app.use(express.json({limit:'2mb'}));
app.use((req,res,next)=>{res.set('Cache-Control','no-store');next()});
app.use(express.static(path.join(__dirname,'..','public')));
function broadcast(message){const data=JSON.stringify(message);for(const c of clients)if(c.readyState===WebSocket.OPEN)c.send(data)}
const obs=new ObsService(broadcast);
const discord=new DiscordNotifier(()=>db.getSettings());
const actions=new ActionEngine({getRules:()=>db.getRules(),broadcast,obs});
let hotkeySceneIndex=0;
async function runHotkey(action){broadcast({type:'hotkey',action});if(action==='timer_toggle'){const current=await db.getGame('timer');if(current)await db.finishGame(current.id);else await db.startGame('timer',{durationSeconds:300})}if(action==='wheel_spin'){const current=await db.getGame('wheel');if(current)await db.spinGame(current.id);else{const id=await db.startGame('wheel',{options:['Premiu 1','Premiu 2','Premiu 3','Bonus']});await db.spinGame(id)}}if(action==='song_next')await db.advanceSong();if(action==='obs_scene_next'){const scenes=await obs.getScenes();if(scenes.length){hotkeySceneIndex=(hotkeySceneIndex+1)%scenes.length;await obs.setScene(scenes[hotkeySceneIndex].sceneName)}}broadcast({type:'hotkey_done',action})}
const hotkeys=new HotkeyService(runHotkey);
async function processAuxiliary(event){const [commands,sounds]=await Promise.all([db.listCommands(),db.listSoundAlerts()]);if(event.type==='chat'){const text=String(event.comment||'').trim();const command=text.split(/\s+/)[0].toLowerCase();const match=commands.find(c=>c.enabled&&String(c.command_name).toLowerCase()===command);if(match){broadcast({type:'chat_response',command:match.command_name,response:match.response_text,event});if(match.response_text)broadcast({type:'tts',text:String(match.response_text).replace(/\{username\}/g,event.displayName||event.uniqueId||'viewer')});await actions.run(match.actions,event)}}for(const sound of sounds){const c=sound.triggerConfig||{};if(!sound.enabled||sound.trigger_type!==event.type)continue;if(c.giftName&&String(c.giftName).toLowerCase()!==String(event.giftName||'').toLowerCase())continue;if(c.minCoins&&Number(event.coins||0)<Number(c.minCoins))continue;broadcast({type:'sound',sound:{id:sound.id,name:sound.name,url:sound.file_path,volume:Number(sound.volume||1)},event})}}
async function processEvent(event){state.lastEvent=event;try{if(state.db){await db.saveEvent(event);await db.upsertViewer(event);await db.applyEventToGoals(event);await db.applyEventToGames(event);await actions.process(event);await processAuxiliary(event);await discord.event(event)}}catch(error){broadcast({type:'database_error',message:error.message})}broadcast({type:'event',event})}
const tiktok=new TikTokService(processEvent,status=>{Object.assign(state,status);broadcast({type:'status',status})},gifts=>{state.gifts=gifts||[];broadcast({type:'gifts',gifts:state.gifts})});
wss.on('connection',client=>{clients.add(client);client.send(JSON.stringify({type:'state',state}));client.on('close',()=>clients.delete(client))});
app.get('/api/status',(_q,r)=>r.json(state));
app.get('/api/hotkeys',(_q,r)=>r.json({enabled:Boolean(hotkeys.proc),bindings:{1:'Ctrl+Alt+F1 • Timer',2:'Ctrl+Alt+F2 • Wheel Spin',3:'Ctrl+Alt+F3 • Next Song',4:'Ctrl+Alt+F4 • Next OBS Scene'}}));
app.post('/api/hotkeys/trigger',async(q,r)=>{try{await runHotkey(String(q.body.action||''));r.json({ok:true})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.get('/api/gifts',(_q,r)=>r.json(state.gifts||[]));
app.post('/api/connect',async(q,r)=>{try{state.username=String(q.body.username||'').trim();await db.resetStreamGoals();await tiktok.connect(state.username);r.json({ok:true,state})}catch(e){state.connected=false;r.status(400).json({ok:false,error:e.message})}});
app.post('/api/disconnect',async(_q,r)=>{await tiktok.disconnect();state.connected=false;broadcast({type:'status',status:state});r.json({ok:true})});
app.post('/api/obs/connect',async(q,r)=>{try{await obs.connect(q.body.url||'ws://127.0.0.1:4455',q.body.password||'');state.obsConnected=true;r.json({ok:true,scenes:await obs.getScenes()})}catch(e){state.obsConnected=false;r.status(400).json({ok:false,error:e.message})}});
app.post('/api/obs/disconnect',async(_q,r)=>{await obs.disconnect();state.obsConnected=false;r.json({ok:true})});
app.get('/api/obs/scenes',async(_q,r)=>{try{r.json({scenes:await obs.getScenes()})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/obs/scene',async(q,r)=>{try{await obs.setScene(String(q.body.scene||''));r.json({ok:true,scene:q.body.scene})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.get('/api/rules',async(_q,r)=>{try{r.json(await db.getRules())}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/rules',async(q,r)=>{try{const id=await db.createRule(q.body);r.json({ok:true,id})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.put('/api/rules/:id',async(q,r)=>{try{await db.updateRule(q.params.id,q.body);r.json({ok:true})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.delete('/api/rules/:id',async(q,r)=>{try{await db.deleteRule(q.params.id);r.json({ok:true})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.get('/api/viewers/stats',async(_q,r)=>{try{r.json(await db.getViewerStats())}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/overlay/:name/data',async(q,r)=>{try{r.json(await db.getOverlayData(q.params.name))}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/profiles',async(_q,r)=>{try{r.json(await db.getProfiles())}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/profiles',async(q,r)=>{try{r.json({ok:true,id:await db.createProfile(q.body.name,q.body.username,q.body.plan||'premium')})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.get('/api/settings',async(_q,r)=>{try{r.json(await db.getSettings())}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/settings',async(q,r)=>{try{for(const [key,value] of Object.entries(q.body))await db.saveSetting(key,value);r.json({ok:true})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.get('/api/goals',async(_q,r)=>{try{r.json(await db.listGoals())}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/goals',async(q,r)=>{try{r.json({ok:true,id:await db.saveGoal(q.body)})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.put('/api/goals/:id',async(q,r)=>{try{await db.updateGoal(q.params.id,q.body);r.json({ok:true})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.delete('/api/goals/:id',async(q,r)=>{try{await db.deleteGoal(q.params.id);r.json({ok:true})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.get('/api/chat/commands',async(_q,r)=>{try{r.json(await db.listCommands())}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/chat/commands',async(q,r)=>{try{r.json({ok:true,id:await db.saveCommand(q.body)})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.delete('/api/chat/commands/:id',async(q,r)=>{try{await db.deleteCommand(q.params.id);r.json({ok:true})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.get('/api/songs',async(_q,r)=>{try{r.json(await db.listSongs())}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/songs',async(q,r)=>{try{r.json({ok:true,id:await db.addSong(q.body)})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.patch('/api/songs/:id',async(q,r)=>{try{await db.updateSong(q.params.id,q.body.status);r.json({ok:true})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.get('/api/sounds',async(_q,r)=>{try{r.json(await db.listSoundAlerts())}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/uploads/sound',upload.single('file'),(q,r)=>{if(!q.file)return r.status(400).json({error:'Selectează un fișier audio valid.'});r.json({ok:true,url:`/uploads/sounds/${q.file.filename}`,name:q.file.originalname})});
app.post('/api/sounds',async(q,r)=>{try{r.json({ok:true,id:await db.saveSoundAlert(q.body)})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.get('/api/overlays',async(_q,r)=>{try{r.json(await db.listOverlays())}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/overlays',async(q,r)=>{try{await db.saveOverlay(q.body);r.json({ok:true})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.get('/api/games/:type',async(q,r)=>{try{r.json(await db.getGame(q.params.type))}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/games/:type/start',async(q,r)=>{try{r.json({ok:true,id:await db.startGame(q.params.type,q.body||{})})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.post('/api/games/:id/spin',async(q,r)=>{try{r.json({ok:true,game:await db.spinGame(q.params.id)})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.post('/api/games/:id/finish',async(q,r)=>{try{await db.finishGame(q.params.id);r.json({ok:true})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.post('/api/test-event',async(q,r)=>{const type=q.body.type||'gift';const event={type,uniqueId:q.body.uniqueId||'local_test',displayName:q.body.displayName||'Local test',giftName:type==='gift'?(q.body.giftName||'Rose'):null,coins:Number(q.body.coins??(type==='gift'?1:0)),quantity:Number(q.body.quantity??1),comment:q.body.comment||'',payload:{test:true}};try{await processEvent(event);r.json({ok:true,event})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.get('/overlay/:name',(q,r)=>{const mainOverlays=new Set(['firework','snow','social','emojify']);const file=mainOverlays.has(q.params.name)?'overlay.html':'advanced.html';r.sendFile(path.join(__dirname,'..','public','overlays',file))});
(async()=>{try{await db.checkDatabase();await migrate();state.db=true}catch(e){console.warn('Baza MySQL nu este conectata:',e.message)}const port=Number(process.env.PORT||3000);server.listen(port,()=>{hotkeys.start();console.log(`TikLiveTools: http://localhost:${port}`)})})();
