const crypto=require('crypto');
class SpotifyService{
  constructor(db){this.db=db;this.pendingState=null}
  get config(){return {clientId:process.env.SPOTIFY_CLIENT_ID||'',clientSecret:process.env.SPOTIFY_CLIENT_SECRET||'',redirectUri:process.env.SPOTIFY_REDIRECT_URI||'http://localhost:3000/api/spotify/callback'}}
  isConfigured(){const c=this.config;return Boolean(c.clientId&&c.clientSecret)}
  async settings(){return this.db.getSettings()}
  async authorizationUrl(){if(!this.isConfigured())throw new Error('Configurează SPOTIFY_CLIENT_ID și SPOTIFY_CLIENT_SECRET în .env.');this.pendingState=crypto.randomBytes(24).toString('hex');const c=this.config;const p=new URLSearchParams({client_id:c.clientId,response_type:'code',redirect_uri:c.redirectUri,state:this.pendingState,scope:'user-read-private user-read-email user-modify-playback-state user-read-currently-playing user-read-playback-state'});return `https://accounts.spotify.com/authorize?${p}`}
  async callback(code,state){if(!code||state!==this.pendingState)throw new Error('Starea OAuth Spotify nu este validă.');this.pendingState=null;const c=this.config;const body=new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:c.redirectUri});const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${c.clientId}:${c.clientSecret}`).toString('base64')}`,'content-type':'application/x-www-form-urlencoded'},body});const data=await r.json();if(!r.ok)throw new Error(data.error_description||'Spotify token exchange failed');await this.saveToken(data);const me=await this.request('/v1/me');await this.db.saveSetting('spotifyUser',JSON.stringify({id:me.id,displayName:me.display_name}));return me}
  async saveToken(data){const now=Date.now();await this.db.saveSetting('spotifyAccessToken',data.access_token);if(data.refresh_token)await this.db.saveSetting('spotifyRefreshToken',data.refresh_token);await this.db.saveSetting('spotifyTokenExpiresAt',String(now+Number(data.expires_in||3600)*1000));await this.db.saveSetting('spotifyScope',data.scope||'')}
  async accessToken(){const s=await this.settings(),expires=Number(s.spotifyTokenExpiresAt||0);if(s.spotifyAccessToken&&expires>Date.now()+60000)return s.spotifyAccessToken;if(!s.spotifyRefreshToken||!this.isConfigured())return null;const c=this.config;const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{Authorization:`Basic ${Buffer.from(`${c.clientId}:${c.clientSecret}`).toString('base64')}`,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:s.spotifyRefreshToken})});const data=await r.json();if(!r.ok)throw new Error(data.error_description||'Spotify refresh failed');await this.saveToken({...data,refresh_token:data.refresh_token||s.spotifyRefreshToken});return data.access_token}
  async request(path,options={}){const token=await this.accessToken();if(!token)throw new Error('Spotify nu este conectat.');const r=await fetch(`https://api.spotify.com${path}`,{...options,headers:{Authorization:`Bearer ${token}`,...(options.headers||{})}});if(r.status===204)return null;const data=await r.json();if(!r.ok)throw new Error(data.error?.message||`Spotify API ${r.status}`);return data}
  async status(){const s=await this.settings();return {configured:this.isConfigured(),connected:Boolean(s.spotifyRefreshToken||s.spotifyAccessToken),user:s.spotifyUser?JSON.parse(s.spotifyUser):null}}
  async search(q){if(!q)throw new Error('Introdu un termen de căutare.');const data=await this.request(`/v1/search?${new URLSearchParams({q,type:'track',limit:'10'})}`);return (data.tracks?.items||[]).map(t=>({id:t.id,uri:t.uri,title:t.name,artist:t.artists?.map(a=>a.name).join(', '),album:t.album?.name,url:t.external_urls?.spotify}))}
  async queue(uri){if(!/^spotify:track:[A-Za-z0-9]+$/.test(String(uri||'')))throw new Error('URI Spotify invalid.');await this.request(`/v1/me/player/queue?${new URLSearchParams({uri})}`,{method:'POST'});return {ok:true,uri}}
}
module.exports=SpotifyService;
