const {WebcastPushConnection}=require('tiktok-live-connector');

function userFields(data={}){const user=data.user||data;return {uniqueId:user.uniqueId||user.unique_id||data.uniqueId||data.unique_id,displayName:user.nickname||user.displayName||data.nickname||data.displayName||data.uniqueId,avatarUrl:user.profilePictureUrl||user.avatarUrl||data.profilePictureUrl||data.avatarUrl,isModerator:Boolean(user.isModerator||data.isModerator),isSubscriber:Boolean(user.isSubscriber||data.isSubscriber)}}
function normalizeGift(data={}){const u=userFields(data),details=data.giftDetails||{},extended=data.extendedGiftInfo||{};return {...u,giftName:data.giftName||details.giftName||extended.name||data.name,giftId:data.giftId||details.giftId||data.gift_id,coins:Number(data.diamondCount??data.coinCount??extended.diamondCount??extended.cost??data.diamond_count??0),quantity:Number(data.repeatCount||data.repeat_count||1),giftType:Number(details.giftType??data.giftType??data.gift_type??0),repeatEnd:Boolean(data.repeatEnd??data.repeat_end??true)}}
function normalizeLike(data={}){const u=userFields(data);return {...u,quantity:Number(data.likeCount||data.like_count||1),totalLikeCount:Number(data.totalLikeCount||data.total_like_count||0)}}
class TikTokService{
  constructor(onEvent,onStatus,onCatalog){this.onEvent=onEvent;this.onStatus=onStatus;this.onCatalog=onCatalog;this.connection=null}
  async connect(username,sessionId){if(!username)throw new Error('Introdu username-ul TikTok.');if(!sessionId)throw new Error('Pentru conexiune locală fără serviciu extern, completează cookie-ul TikTok sessionid în Setup.');await this.disconnect();const opts={enableExtendedGiftInfo:true,processInitialData:true,fetchRoomInfoOnConnect:true,enableWebsocketUpgrade:true,sessionId:String(sessionId).trim()};this.connection=new WebcastPushConnection(username.replace(/^@/,''),opts);const emit=(type,d={})=>this.onEvent({type,...d,payload:d});
    this.connection.on('connected',s=>this.onStatus({connected:true,roomId:s.roomId,username}));this.connection.on('disconnected',i=>this.onStatus({connected:false,reason:i?.reason||'Disconnected'}));this.connection.on('streamEnd',()=>this.onStatus({connected:false,reason:'Stream ended'}));this.connection.on('error',e=>this.onStatus({connected:false,error:String(e?.message||e)}));
    this.connection.on('chat',d=>emit('chat',{...userFields(d),comment:d.comment||d.content||''}));this.connection.on('follow',d=>emit('follow',userFields(d)));this.connection.on('share',d=>emit('share',userFields(d)));this.connection.on('social',d=>{if(d.displayType==='follow'||d.followInfo)emit('follow',userFields(d));else if(d.displayType==='share'||d.shareInfo)emit('share',userFields(d))});this.connection.on('like',d=>emit('like',normalizeLike(d)));this.connection.on('gift',d=>{const gift=normalizeGift(d);if(gift.giftType===1&&!gift.repeatEnd)return;delete gift.giftType;delete gift.repeatEnd;emit('gift',gift)});this.connection.on('member',d=>emit('join',{...userFields(d),memberCount:Number(d.memberCount||d.member_count||0)}));this.connection.on('subscribe',d=>emit('subscribe',userFields(d)));this.connection.on('questionNew',d=>emit('question',{...userFields(d),comment:d.question||d.content||''}));this.connection.on('linkMicBattle',d=>emit('battle',{payload:d}));this.connection.on('roomUser',d=>this.onStatus({roomStats:{viewerCount:Number(d.viewerCount||d.viewer_count||0),topGifters:(d.ranksList||d.topGifters||[]).slice(0,10).map(x=>({uniqueId:x.user?.uniqueId||x.uniqueId,displayName:x.user?.nickname||x.displayName,coins:Number(x.coinCount||x.coins||0)}))}}));
    const state=await this.connection.connect();try{const gifts=await this.connection.getAvailableGifts();this.onCatalog(gifts||[])}catch{this.onCatalog([])}return state}
  async disconnect(){if(this.connection){try{this.connection.disconnect()}catch{}this.connection=null;this.onCatalog([])}}
  async sendMessage(text){if(!this.connection||!text)throw new Error('TikTok LIVE nu este conectat.');return this.connection.sendMessage(String(text))}
}
module.exports=TikTokService;module.exports.normalizeGift=normalizeGift;module.exports.normalizeLike=normalizeLike;
